mysql:
  dns: root:root@tcp(127.0.0.1:33067)/ginchat?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "127.0.0.1:13001"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
oss:
  Endpoint: "https://oss-cn-beijing.aliyuncs.com"
  AccessKeyId: "LTAI5tQdpsht36XJqYZevPGn"
  AccessKeySecret: "dyThns69pEwBcGl1AjBby1YsGEyDcm"
  Bucket : "xichen-server"

timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

port:
  server: ":8082"
  udp: 3001
